"""Add password reset columns to user table

Revision ID: 7aef7ef279d7
Revises: 4ec060d4d095
Create Date: 2026-01-08 12:45:31.168179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7aef7ef279d7'
down_revision: Union[str, Sequence[str], None] = '4ec060d4d095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_column('user', 'password_reset_expires')
    op.drop_column('user', 'password_reset_token')
    # ### end Alembic commands ###
